apiVersion: apps/v1
kind: Deployment
metadata:
  name: forest-gateway
  namespace: forest
spec:
  replicas: 3
  selector:
    matchLabels:
      name: forest-pod
  template:
    metadata:
      labels:
        name: forest-pod
    spec:
      containers:
        - name: forest-gateway-proxy
          image: forest-gateway:latest
          imagePollPolicy: Never
          ports:
            - containerPort: 8080
            - containerPort: 4433
---
apiVersion: apps/v1
kind: Service
metadata:
  name: forest-gateway
  namespace: forest
spec:
  ports:
    - port: 8080
      name: "http"
      targetPort: 8080
      protocol: TCP
      nodePort: 30080
    - port: 4433
      name: "https"
      targetPort: 4433
      protocol: TCP
      nodePort: 30443
  type: NodePort
  selector:
    name: forest-gateway
