# this is redis config file
[list]
    [list.default]
        proxy_list = ["127.0.0.1:6380"]
        data_source_name = "redis://default:123456@127.0.0.1:6380/0"
        conn_timeout = 500
        read_timeout = 1000
        write_timeout = 1000
        max_active = 200
        max_idle = 500
        password = 123456