basePath: /api
definitions:
  adminDto.AdminInfoOutput:
    properties:
      avatar:
        type: string
      id:
        type: integer
      introduction:
        type: string
      login_time:
        type: string
      name:
        type: string
      roles:
        items:
          type: string
        type: array
    type: object
  adminDto.AdminLoginInput:
    properties:
      password:
        example: "123456"
        type: string
      username:
        example: admin
        type: string
    required:
    - password
    - username
    type: object
  adminDto.ChangePwdInput:
    properties:
      password:
        description: 密码
        example: "123456"
        type: string
    required:
    - password
    type: object
  commonDto.TokensOutput:
    properties:
      access_token:
        description: access_token
        type: string
      expires_in:
        description: expires_in
        type: integer
      scope:
        description: scope
        type: string
      token_type:
        description: token_type
        type: string
    type: object
  model.AccessControl:
    properties:
      black_list:
        type: string
      clientip_flow_limit:
        type: integer
      createdAt:
        type: string
      id:
        type: integer
      isDeleted:
        type: boolean
      open_auth:
        type: boolean
      service_flow_limit:
        type: integer
      serviceInfoID:
        type: integer
      updatedAt:
        type: string
      white_host_name:
        type: string
      white_list:
        type: string
    type: object
  model.GrpcRule:
    properties:
      header_transfor:
        type: string
      id:
        type: integer
      port:
        type: integer
      service_id:
        type: integer
    type: object
  model.HttpRule:
    properties:
      header_transfor:
        type: string
      id:
        type: integer
      need_https:
        type: boolean
      need_strip_uri:
        type: boolean
      need_websocket:
        type: boolean
      rule:
        type: string
      rule_type:
        type: integer
      service_id:
        type: integer
      url_rewrite:
        type: string
    type: object
  model.LoadBalance:
    properties:
      check_interval:
        type: integer
      check_method:
        type: integer
      check_timeout:
        type: integer
      forbid_list:
        type: string
      id:
        type: integer
      ip_list:
        type: string
      round_type:
        type: integer
      service_id:
        type: integer
      upstream_connect_timeout:
        type: integer
      upstream_header_timeout:
        type: integer
      upstream_idle_timeout:
        type: integer
      upstream_max_idle:
        type: integer
      weight_list:
        type: string
    type: object
  model.Service:
    properties:
      accessControl:
        $ref: '#/definitions/model.AccessControl'
      createdAt:
        type: string
      grpcRole:
        $ref: '#/definitions/model.GrpcRule'
      httpRule:
        $ref: '#/definitions/model.HttpRule'
      id:
        type: integer
      isDeleted:
        type: boolean
      load_type:
        type: integer
      loadBalance:
        $ref: '#/definitions/model.LoadBalance'
      service_desc:
        type: string
      service_name:
        type: string
      tcpRole:
        $ref: '#/definitions/model.TcpRule'
      updatedAt:
        type: string
    type: object
  model.ServiceDetail:
    properties:
      access_control:
        $ref: '#/definitions/model.AccessControl'
      grpc_rule:
        $ref: '#/definitions/model.GrpcRule'
      http_rule:
        $ref: '#/definitions/model.HttpRule'
      info:
        $ref: '#/definitions/model.Service'
      load_balance:
        $ref: '#/definitions/model.LoadBalance'
      tcp_rule:
        $ref: '#/definitions/model.TcpRule'
    type: object
  model.TcpRule:
    properties:
      id:
        type: integer
      port:
        type: integer
      service_id:
        type: integer
    type: object
  public.Response:
    properties:
      data: {}
      errmsg:
        type: string
      errno:
        $ref: '#/definitions/public.ResponseCode'
      stack: {}
      trace_id: {}
    type: object
  public.ResponseCode:
    enum:
    - 0
    - 1
    - 2
    - 3
    - 401
    - 1000
    - 2001
    type: integer
    x-enum-varnames:
    - SuccessCode
    - UndefErrorCode
    - ValidErrorCode
    - InternalErrorCode
    - InvalidRequestErrorCode
    - CustomizeCode
    - GROUPALL_SAVE_FLOWERROR
  serviceDto.ServiceListItemOutput:
    properties:
      id:
        description: id
        type: integer
      load_type:
        description: 类型
        type: integer
      qpd:
        description: qpd
        type: integer
      qps:
        description: qps
        type: integer
      service_addr:
        description: 服务地址
        type: string
      service_desc:
        description: 服务描述
        type: string
      service_name:
        description: 服务名称
        type: string
      total_node:
        description: 节点数
        type: integer
    type: object
  serviceDto.ServiceListOutput:
    properties:
      list:
        items:
          $ref: '#/definitions/serviceDto.ServiceListItemOutput'
        type: array
      total:
        type: integer
    type: object
host: localhost:8880
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Go-Gateway  API
  version: "1.0"
paths:
  /admin/change_pwd:
    post:
      consumes:
      - application/json
      description: 修改密码
      operationId: /admin/change_pwd
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/adminDto.ChangePwdInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/public.Response'
            - properties:
                data:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 修改密码
      tags:
      - Admin
  /admin/info:
    get:
      consumes:
      - application/json
      description: 管理员信息
      operationId: /admin/info
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/public.Response'
            - properties:
                data:
                  $ref: '#/definitions/adminDto.AdminInfoOutput'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 管理员信息
      tags:
      - Admin
  /admin_login/login:
    post:
      consumes:
      - application/json
      description: 管理员登陆
      operationId: /admin_login/login
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/adminDto.AdminLoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/public.Response'
            - properties:
                data:
                  $ref: '#/definitions/commonDto.TokensOutput'
              type: object
      summary: 管理员登陆
      tags:
      - Admin
  /service:
    get:
      consumes:
      - application/json
      description: 服务列表
      operationId: /service
      parameters:
      - description: 关键词
        in: query
        name: info
        type: string
      - description: 每页个数
        in: query
        name: page_size
        required: true
        type: integer
      - description: 当前页数
        in: query
        name: page_no
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/public.Response'
            - properties:
                data:
                  $ref: '#/definitions/serviceDto.ServiceListOutput'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 服务列表
      tags:
      - Service
  /service/{service_id}:
    get:
      consumes:
      - application/json
      description: 服务列表
      operationId: /service/{service_id}
      parameters:
      - description: 服务id
        in: path
        name: service_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/public.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.ServiceDetail'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 服务详情
      tags:
      - Service
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
  OAuth2AccessCode:
    authorizationUrl: https://example.com/oauth/authorize
    flow: accessCode
    scopes:
      admin: ' Grants read and write access to administrative information'
    tokenUrl: https://example.com/oauth/token
    type: oauth2
  OAuth2Application:
    flow: application
    scopes:
      admin: ' Grants read and write access to administrative information'
      write: ' Grants write access'
    tokenUrl: https://example.com/oauth/token
    type: oauth2
  OAuth2Implicit:
    authorizationUrl: https://example.com/oauth/authorize
    flow: implicit
    scopes:
      admin: ' Grants read and write access to administrative information'
      write: ' Grants write access'
    type: oauth2
  OAuth2Password:
    flow: password
    scopes:
      admin: ' Grants read and write access to administrative information'
      read: ' Grants read access'
      write: ' Grants write access'
    tokenUrl: https://example.com/oauth/token
    type: oauth2
swagger: "2.0"
x-extension-openapi:
  example: value on a json format
